global:
  resolve_timeout: 5m

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://localhost:5000/capture_alerts'
        send_resolved: true  

route:
  group_by: ['alertname']  
  receiver: 'webhook-receiver'  
  repeat_interval: 1h  
  group_wait: 30s  
  group_interval: 5m  


  
